<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="MAIN" Id="{50158451-d374-4957-970b-65b4e1d88bf2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fb3AxisRobot	:FB_3AxisRobot;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[fb3AxisRobot();

(*
プログラム作成メモ
ワークを掴めていることの確認追加

アラーム作成
E Stopボタン毎にアラーム分け
CPアラーム
パワーサプライアラーム
スイッチングハブアラーム
GOTアラーム
CycleTimeExceededのどのPLCタスクで発生しているかのアラーム
停電検知のアラーム　と　そのリセット「bPowerFailDetectReset」あり

IPCのCPU温度、FAN回転数の確認

1s UPS 関係の制御
*)

]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="7" Count="0" />
      <LineId Id="16" Count="0" />
      <LineId Id="10" Count="2" />
      <LineId Id="31" Count="0" />
      <LineId Id="22" Count="0" />
      <LineId Id="37" Count="0" />
      <LineId Id="25" Count="0" />
      <LineId Id="28" Count="2" />
      <LineId Id="36" Count="0" />
      <LineId Id="40" Count="0" />
      <LineId Id="27" Count="0" />
      <LineId Id="26" Count="0" />
      <LineId Id="33" Count="0" />
      <LineId Id="32" Count="0" />
      <LineId Id="13" Count="0" />
      <LineId Id="233" Count="0" />
      <LineId Id="232" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>