<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="MAIN" Id="{50158451-d374-4957-970b-65b4e1d88bf2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	fb3AxisRobot	:FB_3AxisRobot;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[fb3AxisRobot();

(*
プログラム作成メモ
ワークを掴めていることの確認追加

アラーム作成
E Stopボタン毎にアラーム分け
CPアラーム
パワーサプライアラーム
スイッチングハブアラーム
GOTアラーム
CycleTimeExceededのどのPLCタスクで発生しているかのアラーム
停電検知のアラーム　と　そのリセット「bPowerFailDetectReset」あり

IPCのCPU温度、FAN回転数の確認

1s UPS 関係の制御
*)

]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="1" Count="20" />
    </LineIds>
  </POU>
</TcPlcObject>