<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="P_Vision" Id="{12aa390b-17e5-4f54-a4d0-60c6f0bb99e7}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Vision
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_DNNVision();]]></ST>
    </Implementation>
    <LineIds Name="P_Vision">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>