<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_EtherCATTopologyDiagnosis" Id="{6fe1c4c8-cec6-4d64-a8c8-dffaa5ef8150}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_EtherCATTopologyDiagnosis
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_EtherCATTopologyDiagnosis">
      <LineId Id="1" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>