<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{50158451-d374-4957-970b-65b4e1d88bf2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[P_Safety();
P_Alarm();
P_Patlite();
P_BasicMotion();
P_WriteMotion();
P_MitsubishiCommunication();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="7" Count="5" />
    </LineIds>
  </POU>
</TcPlcObject>